# Initial joint configuration for CS63 arm + DG3F gripper
# All angles are in radians
# Arm points towards positive X-axis

arm_joints:
  shoulder_pan_joint: 0                    # 0 degrees
  shoulder_lift_joint: -2.356194490192345  # -135 degrees (-3π/4)
  elbow_joint: -1.5707963267948966         # -90 degrees (-π/2)
  wrist_1_joint: -1.5707963267948966       # -90 degrees (-π/2)
  wrist_2_joint: -1.5707963267948966       # -90 degrees (-π/2)
  wrist_3_joint: 0                         # 0 degrees

gripper_joints:
  # Finger 1
  F1M1: 0.0
  F1M2: 0.0
  F1M3: 0.7853981633974483  # 45 degrees
  F1M4: 0.5235987755982988  # 30 degrees
  
  # Finger 2
  F2M1: -0.4363323129985824  # -25 degrees
  F2M2: 0.0
  F2M3: 0.7853981633974483  # 45 degrees
  F2M4: 0.5235987755982988  # 30 degrees
  
  # Finger 3
  F3M1: 0.4363323129985824  # 25 degrees
  F3M2: 0.0
  F3M3: 0.7853981633974483  # 45 degrees
  F3M4: 0.5235987755982988  # 30 degrees